#...............................................................................
# 1. - Initialize Session #### 
#...............................................................................

cat("\014")
rm(list=ls()) 

# Installs libraries 

list.of.packages <- c("epanet2toolkit","epanetReader","data.table","tidyverse") 

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]

if(length(new.packages)) install.packages(new.packages,dependencies=TRUE)

lapply(list.of.packages, require, character.only = TRUE)

rm(list.of.packages,new.packages) # remove


# initialize files paths and files

dir_work   <-  getwd()
dir_report <-  file.path(dir_work,"reports") 
dir_data   <-  file.path(dir_work,"data")  
dir_bin    <-  file.path(dir_work,"reports")

# The input processor module receives a description of the network 
# being simulated from an external input file (*.INP)
file_inp     <- file.path(dir_data,   "prv_01.inp")
file_report  <- file.path(dir_report, "prv_01.rpt")
file_bin     <- file.path(dir_report, "prv_01.bin")

# Read network information from an *.inp
net_input_01  <- read.inp(file_inp)

entries <- summary(net_input_01)

entries$entryCounts

# Retrieve summary information about the network.
names(net_input_01)

summary(net_input_01)
summary(net_input_01$Junctions)
summary(net_input_01$Emitters)

net_input_01$Patterns

str(net_input_01$Patterns)
length(net_input_01$Patterns$PT0001)

# A basic network plot 

# plot(net_01$Patterns$PT0001)
# net_01$Junctions
# plot(net_01)


#...............................................................................
# 2. Running a Full Simulation                                             ####
#    The function ENepanet() runs a full simulation and 
#    writes the results to a file. 
#...............................................................................

ENepanet(file_inp, file_report, file_bin)


# The .rpt file generated by Epanet may be read into R using read.rpt(). 
# The simulation is summarized over junctions, tanks and pipes.

net_report_01 <- read.rpt(file_report) 
summary(net_report_01)

# The default plot of simulation results is a map for time period 00:00:00. 
# Note that the object created from the .inp file is a required argument to 
# make the plot.

# plot( net_report_01, net_01)

# Results for a chosen time period can be retrieved using the subset function.

names(net_report_01)

t000 <- subset(net_report_01$nodeResults, 
               Timestamp == "0:15:00")


