#...............................................................................
# 1. - Initialize Session #### 
#...............................................................................

cat("\014")
rm(list=ls()) 

# Installs libraries 

library(zoo)
library(lubridate)

library(tidyverse)
library(epanetReader)
library(epanet2toolkit)
library(ggfortify)
library(ggthemes)

library(plyr) 
library(reshape2)
library(scales)

# Initialize params

params <- list(net_works     = "prv_01", 
               inlet_valves  = c("PRV_001"),
               time_step     = "hour",
               pattern_start = "2020-1-1 00:30",
               pattern_end   = "2020-1-1 23:30",
               main_nodes    = c("JT-0A-001", "JT-0K-011"))


demad_factor <- list( c( "wd_spring_summer","hw_spring_summer",
                         "wd_summer_break","hw_summer_break",
                         "wd_fall_winter","hw_fall_winter"),
                      c( 0.92, 1.00, 1.09, 0.81, 0.66, 0.95))

# Time Serie Index
idx <- seq( ymd_hm(params$pattern_start), 
            ymd_hm(params$pattern_end), 
            by = params$time_step)


# initialize files paths and files

dir_work   <-  getwd()
dir_report <-  file.path(dir_work,"reports") 
dir_data   <-  file.path(dir_work,"data")  
dir_bin    <-  file.path(dir_work,"reports")
dir_func   <-  file.path(dir_work,"func")

file_inp     <- file.path(dir_data,   paste0(params$net_work,".inp"))
file_report  <- file.path(dir_report, paste0(params$net_work,".rpt"))
file_bin     <- file.path(dir_report, paste0(params$net_work,".bin"))
file_func    <- file.path(dir_func,   "epanet_api_functions.R")

# Load Functions Standard

source(file_func)

# Read network information from an *.inp

net_input_01  <- read.inp(file_inp)

#...............................................................................
# Plot Network
#...............................................................................

# plot(net_input_01)

#...............................................................................
# Plot NODAL Demand Patterns
# nd <- Nodal demands, 
#       wd <- Workdays
#       hw <- weekdays and holidays
# rh <- reservoir heads, 
# ps <- pump schedules, 
# wq <- water quality 
#...............................................................................

patterns <- as.tibble(net_input_01$Patterns) %>% 
            select(starts_with("nd")) %>%          
            as.zoo(idx)

plot_ts_curves(patterns,
               y_limits = c(0.0,2.0),
               m_title  = "NODAL DEMAND PATTERNS",  
               y_lab    = "Multiplier (Avg. = 1.0)")

#...............................................................................
# 2. Running a Full Simulation                                             ####
#    The function ENepanet() runs a full simulation and 
#    writes the results to a file. 
#...............................................................................

ENepanet(file_inp, file_report)

#...............................................................................
# The .rpt file generated by Epanet may be read into R using read.rpt(). 
# The simulation is summarized over junctions, tanks and pipes.
#...............................................................................

net_report_01 <- read.rpt(file_report) 


inlet_flow <- subset(net_report_01$linkResults, 
                     ID == params$inlet_valves) %>%
              as.tibble()  %>%
              select(Flow) %>%
              as.zoo(idx)

d_pressure <- net_report_01$nodeResults %>%
              subset(nodeType == "Junction") %>%
              as.tibble() %>%
              select(ID,timeInSeconds,Pressure) %>%
              dcast(timeInSeconds~ID, 
                    margins = FALSE, 
                    value.var = "Pressure",
                    fun.aggregate = mean)

# gather()  takes multiple columns, and gathers them into key-value pairs: 
#           it makes “wide” data longer.
#
# spread(). takes two columns (key & value) and spreads in to multiple columns,
#           it makes “long” data wider.



plot_ts_curves(inlet_flow,
               y_limits = c(0.0,25),
               m_title  = "Inlet Flow (l/s)",
               y_lab    = "Flow (l/s)")

# inhabitants = aprox. 10,000
# consum about 125 l/hab/day
# round(sum(inlet_flow)*((60*60)/125.0),0)






#...............................................................................
# ACTUAL STATUS MARKER !!!!!!!
# https://help.github.com/articles/adding-an-existing-project-to-github-using-the-command-line/
#...............................................................................
