#...............................................................................
# 1. - Initialize Session #### 
#...............................................................................

cat("\014")
rm(list=ls()) 

# Initialize params

params <- list(net_works = c("prv_01"))

# Installs libraries 

list.of.packages <- c("epanet2toolkit","epanetReader",
                      "data.table","tidyverse",
                      "ggplot2", "animation") 

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]

if(length(new.packages)) install.packages(new.packages,dependencies=TRUE)

lapply(list.of.packages, require, character.only = TRUE)

rm(list.of.packages,new.packages) # remove


# initialize files paths and files

dir_work   <-  getwd()
dir_report <-  file.path(dir_work,"reports") 
dir_data   <-  file.path(dir_work,"data")  
dir_bin    <-  file.path(dir_work,"reports")

# The input processor module receives a description of the network 
# being simulated from an external input file (*.INP)
file_inp     <- file.path(dir_data,   paste(params$net_work,".inp", sep=""))
file_report  <- file.path(dir_report, paste(params$net_work,".rpt", sep=""))
file_bin     <- file.path(dir_report, paste(params$net_work,".bin", sep=""))

# Read network information from an *.inp

net_input_01  <- read.inp(file_inp)
entries       <- summary(net_input_01)
entries$entryCounts

# Retrieve summary information about the network.
names(net_input_01)

summary(net_input_01)
summary(net_input_01$Junctions)
summary(net_input_01$Emitters)

net_input_01$Patterns

str(net_input_01$Patterns)
length(net_input_01$Patterns$PT0001)

# A basic network plot 
# plot(net_input_01$Patterns$PT0001)
# plot(net_input_01)

#...............................................................................
# 2. Running a Full Simulation                                             ####
#    The function ENepanet() runs a full simulation and 
#    writes the results to a file. 
#
# REMEBER !!!
# Add the line 'Nodes All' to the [REPORT] section of the .inp file.
# Add the line 'Links All' to the [REPORT] section of the .inp file.
#...............................................................................

ENepanet(file_inp, file_report)

# The .rpt file generated by Epanet may be read into R using read.rpt(). 
# The simulation is summarized over junctions, tanks and pipes.

net_report_01 <- read.rpt(file_report) 
summary(net_report_01)

# Results for a chosen time period can be retrieved using the subset function.

names(net_report_01)

t000 <- subset(net_report_01$nodeResults, 
               Timestamp == "0:15:00")



#unique time stamps
ts   <- unique(net_report_01$nodeResults$Timestamp)
imax <- length(ts)

# generate animation of plots at each time step
saveHTML(
  for( i in 1:imax){
    plot(net_report_01, net_input_01, Timestep = ts[i]) 
  }
)
